# Generated by Django 4.2 on 2023-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactmdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.FileField(upload_to='blog/images')),
                ('contactprob', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='submitform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='blog/images')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('content', models.TextField()),
                ('subheading1', models.CharField(default='', max_length=60)),
                ('content1', models.TextField(default='')),
                ('subheading2', models.CharField(default='', max_length=60)),
                ('content2', models.TextField()),
                ('subheading3', models.CharField(max_length=60)),
                ('content3', models.TextField()),
                ('subheading4', models.CharField(max_length=60)),
                ('content4', models.TextField()),
                ('subheading5', models.CharField(max_length=60)),
                ('content5', models.TextField()),
                ('subheading6', models.CharField(max_length=60)),
                ('content6', models.TextField()),
                ('subheading7', models.CharField(max_length=60)),
                ('content7', models.TextField()),
                ('subheading8', models.CharField(max_length=60)),
                ('content8', models.TextField()),
                ('subheading9', models.CharField(max_length=60)),
                ('content9', models.TextField()),
                ('subheading10', models.CharField(max_length=60)),
                ('content10', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='topposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_topic', models.CharField(max_length=60)),
                ('top_file', models.FileField(upload_to='blog/images')),
                ('top_slug', models.CharField(max_length=130)),
                ('top_content', models.TextField()),
            ],
        ),
    ]
