# Generated by Django 4.2 on 2023-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_submitform_content10_alter_submitform_content2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='subheading1',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
