# Generated by Django 4.2 on 2023-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_submitform_subheading1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='content9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading10',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading4',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading5',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading6',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading7',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading8',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='subheading9',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
