# Generated by Django 4.2 on 2023-07-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_submitform_content1_alter_submitform_content10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
