# Generated by Django 4.2 on 2023-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_submitform_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='content11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='content12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='content13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='content14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='content15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='content16',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='subheading11',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='submitform',
            name='subheading12',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='submitform',
            name='subheading13',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='submitform',
            name='subheading14',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='submitform',
            name='subheading15',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='submitform',
            name='subheading16',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content16',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_content9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading10',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading11',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading12',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading13',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading14',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading15',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading16',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading4',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading5',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading6',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading7',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading8',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='topposts',
            name='top_subheading9',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
