# Generated by Django 3.2.19 on 2023-09-28 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_submitform_content11_submitform_content12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='ck',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
