# Generated by Django 3.2.19 on 2023-09-28 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_submitform_ck'),
    ]

    operations = [
        migrations.AddField(
            model_name='topposts',
            name='ck',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
