name: Pull Docker Image from Google Artifact Registry

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter the full Docker image name"
        required: true
        type: string
        default: "asia-south1-docker.pkg.dev/swarna-380521/docker-staging/hello-app:1.0"

jobs:
  pull_gar_image:
    runs-on: ubuntu-latest

    steps:
      - name: Print Docker Image Name
        run: echo "Docker Image Name: ${{ github.event.inputs.name }}"

      - name: Authenticate with Google Artifact Registry
        run: |
          echo "${{ secrets.GCR_JSON_KEY }}" | docker login -u _json_key --password-stdin https://asia-south1-docker.pkg.dev

      - name: Pull Docker Image from GAR
        run: |
          echo "Pulling Docker image: ${{ github.event.inputs.name }}"
          docker pull ${{ github.event.inputs.name }}
