name: Print Name Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        type: string
        default: "User"

jobs:
  print_name:
    runs-on: ubuntu-latest

    steps:
      - name: Print only the name
        run: echo "${{ github.event.inputs.name }}"
