name: Build and deploy Python app to Azure Web App - Technicalrealm

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "Triggering User Name"
        required: true
        default: "himanshu"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Input Data
        run: echo "Triggered by: ${{ github.event.inputs.name }}"

      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Technicalrealm'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C94E0F11C794E379C9F1A31AFF0EB52 }}
